### ISSUE TITLE
Data dictionary available?

### ISSUE THREAD

**Issue by tbonza** [presidential-innovation-fellows/fbo-parser#2]
Do you know if there's a data dictionary associated with the parser output? I can guess that PRESOL means "pre-solitication", etc., but it would be really helpful to verify these guesses. Thanks!

**Comment by sawaldt** [comment]
For anyone like me who happens upon this repo/issue you can find most of the information that @tbonza  is looking for in this document: https://www.fbo.gov/downloads/fbo_web_services_technical_documentation.pdf

Just take a quick jump to page 13.

**Comment by tbonza** [comment]
@sawaldt Thanks!
